
class Main {
  public static void main(String[] args) {
    try {
      // code that generates exception
      int divideByZero = 5 / 0;
    }

    catch (ArithmeticException e) {
      System.out.println("ArithmeticException => " + e.getMessage());
    }
    
    finally {
      System.out.println("This is the finally block");
    }
  }
  #new code changes for the feature 301 by vivek
  public class CallingMethodsInSameClass
{
	public static void printOne() {
		System.out.println("Hello World");
	}
}
}